### ISSUE TITLE
Broken characters

### ISSUE THREAD

**Issue by literalEval** [AngelJumbo/sssnake#1]
Does this program use any specific font or terminal ? Because it looks broken in my terminal.
term: alacritty, shell: fish.
![sssnake_issue](https://user-images.githubusercontent.com/62198564/158939083-fe060476-7c00-42e1-9025-32dea0f92b79.png)

**Comment by AngelJumbo** [comment]
The problem migth be the font. what font are you using?

**Comment by SqdNoises** [comment]
i have the same issue,
i am using Monospace Regular with Size 12
![image](https://user-images.githubusercontent.com/85015626/159015319-e2401190-43f9-45d4-8496-ce21d2ab48c2.png)
![image](https://user-images.githubusercontent.com/85015626/159015508-399ef015-d3af-4a40-8613-1f792c64345c.png)

**Comment by AngelJumbo** [comment]
I think I know what Is the issue It has nothing to do with the terminal or the fonts, I will fix It today.

**Comment by WooxHimself** [comment]
> I think I know what Is the issue It has nothing to do with the terminal or the fonts, I will fix It today.

Can you notify us when it's done? Thanks

**Comment by AngelJumbo** [comment]
Can someone with this problem show me the result of the comand "locale" in your system.

**Comment by Literal-Eval** [comment]
![locale](https://user-images.githubusercontent.com/62198564/159312357-37d7b43c-c84a-477e-9f53-92112a121646.png)

**Comment by Literal-Eval** [comment]
![locale](https://user-images.githubusercontent.com/62198564/159312577-6d63451a-96a6-41ac-a7cb-a56486cbefb5.png)

**Comment by AngelJumbo** [comment]
> ![locale](https://user-images.githubusercontent.com/62198564/159312577-6d63451a-96a6-41ac-a7cb-a56486cbefb5.png)

Can you try this?, go to the main.c and un the line 376 remplace "setlocale(LC_ALL, "");" with ” setlocale(LC_ALL, "en_US.UTF-8");  " them make and make install and tell me if it works pls.

**Comment by gamer4life1** [comment]
> > ![locale](https://user-images.githubusercontent.com/62198564/159312577-6d63451a-96a6-41ac-a7cb-a56486cbefb5.png)
> 
> Can you try this?, go to the main.c and in the line 376 replace "setlocale(LC_ALL, "");" with ” setlocale(LC_ALL, "en_US.UTF-8"); " them make and make install and tell me if it works pls.

Does not work

**Comment by AngelJumbo** [comment]
What about setlocale(LC_ALL, "en_US-8"); 

> > > ![locale](https://user-images.githubusercontent.com/62198564/159312577-6d63451a-96a6-41ac-a7cb-a56486cbefb5.png)
> > 
> > 
> > Can you try this?, go to the main.c and in the line 376 replace "setlocale(LC_ALL, "");" with ” setlocale(LC_ALL, "en_US.UTF-8"); " them make and make install and tell me if it works pls.
> 
> Does not work

What about setlocale(LC_ALL, "en_US.utf-8");

**Comment by AngelJumbo** [comment]
There is a command called "unicode_start", can someone execute it to test if this fix the problem?
I mean run:
`
unicode_start
`
then 
`
sssnake -f -S -s 15
`

**Comment by AngelJumbo** [comment]
Well guys, until I get it fixed I added an ascii mode.
It's not the optimal solution as one of the things I wanted to avoid in this project was using ascii characters because they are ugly.

**Comment by AngelJumbo** [comment]
Hey, can someone pull the latest changes and confirm if this issue is now fix?
