### ISSUE TITLE
Distro Packaging

### ISSUE THREAD

**Issue by pagerc** [AngelJumbo/sssnake#2]
Can you add a version and release tarball for distro packagers to reference?

**Comment by AngelJumbo** [comment]
Sure, but at least I want to fix the correct displaying of the unicode characters in all linux systems, I will notify you when it's done.

**Comment by AngelJumbo** [comment]
> Sure, but at least I want to fix the correct displaying of the unicode characters in all linux systems, I will notify you when it's done.

**Comment by AngelJumbo** [comment]
> Sure, but at least I want to fix the correct displaying of the unicode characters in all linux systems, I will notify you when it's done.

**Comment by AngelJumbo** [comment]
> Can you add a version and release tarball for distro packagers to reference?


Sure, but at least I want to fix the correct displaying of the unicode characters in all linux systems, I will notify you when it's done.
