### ISSUE TITLE
Allow the snake to cross the border

### ISSUE THREAD

**Issue by jtyr** [AngelJumbo/sssnake#6]
Either draw a border or allow the snake to cross the border to the other side of the screen.

**Comment by AngelJumbo** [comment]
The ability to cross borders will be optional but I will not draw walls because the number of columns is not always even and if I draw borders there will be gaps between them and the terminal border.

If you want clear borders because the limits are not clear you could try the arcade mode.

**Comment by AngelJumbo** [comment]
@jtyr Hi, I added the option -t / --teleport to be able to cross the border.
