### ISSUE TITLE
Makefile failes

### ISSUE THREAD

**Issue by Nino678190** [AngelJumbo/sssnake#9]
$ git clone https://github.com/AngelJumbo/sssnake.git
cd sssnake
make
make install
Klone nach 'sssnake' …
remote: Enumerating objects: 313, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 313 (delta 78), reused 83 (delta 50), pack-reused 185 (from 1)
Empfange Objekte: 100% (313/313), 278.75 KiB | 674.00 KiB/s, fertig.
Löse Unterschiede auf: 100% (188/188), fertig.
cc -w  main.c autopilot.c xymap.c structs.c snake.c draw.c -lncursesw -o sssnake
make: cc: Datei oder Verzeichnis nicht gefunden
make: *** [makefile:5: sssnake] Fehler 127
cc -w  main.c autopilot.c xymap.c structs.c snake.c draw.c -lncursesw -o sssnake
make: cc: Datei oder Verzeichnis nicht gefunden
make: *** [makefile:5: sssnake] Fehler 127

I use Ubuntu 24.04

**Comment by AngelJumbo** [comment]
hi, it seems like you dont have a c compiler installed, try this before make: sudo apt install build-essential
